import React from 'react';
import { motion, useMotionValue, useSpring, useTransform } from 'framer-motion';
import { Database, Network, Cpu, Zap } from 'lucide-react';

const TiltCard = ({ children, className }) => {
  const x = useMotionValue(0);
  const y = useMotionValue(0);

  const mouseXSpring = useSpring(x);
  const mouseYSpring = useSpring(y);

  const rotateX = useTransform(mouseYSpring, [-0.5, 0.5], ["10deg", "-10deg"]);
  const rotateY = useTransform(mouseXSpring, [-0.5, 0.5], ["-10deg", "10deg"]);

  const handleMouseMove = (e) => {
    const rect = e.target.getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;
    const mouseX = e.clientX - rect.left;
    const mouseY = e.clientY - rect.top;
    const xPct = mouseX / width - 0.5;
    const yPct = mouseY / height - 0.5;
    x.set(xPct);
    y.set(yPct);
  };

  const handleMouseLeave = () => {
    x.set(0);
    y.set(0);
  };

  return (
    <motion.div
      style={{
        rotateX,
        rotateY,
        transformStyle: "preserve-3d",
      }}
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      className={`bento-card ${className} hover:shadow-[0_0_30px_rgba(0,212,255,0.15)]`}
    >
      <div style={{ transform: "translateZ(30px)" }} className="relative z-10 h-full">
        {children}
      </div>
    </motion.div>
  );
};

const Research = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.5 }}
      className="w-full max-w-6xl mx-auto mt-8"
    >
      <h2 className="text-3xl font-black font-sans mb-8 text-glow inline-block">RESEARCH <span className="text-cyber-blue">&</span> METHODOLOGY</h2>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 auto-rows-[250px]">
        {/* Core Architecture */}
        <TiltCard className="col-span-1 md:col-span-2 row-span-1 bg-gradient-to-br from-charcoal to-black">
          <div className="flex flex-col h-full justify-between">
            <div className="flex justify-between items-start">
              <div>
                <h3 className="text-xl font-mono text-white mb-2">Core Architecture</h3>
                <p className="text-sm font-sans text-gray-400 max-w-md">Our detection engine utilizes a multi-modal transformer architecture, cross-referencing spatial artifacts with temporal inconsistencies.</p>
              </div>
              <Network size={32} className="text-cyber-blue" />
            </div>
            <div className="mt-4 flex gap-4">
              <div className="px-3 py-1 bg-cyber-blue/10 border border-cyber-blue/30 rounded text-xs font-mono text-cyber-blue">Vision Transformers</div>
              <div className="px-3 py-1 bg-cyber-blue/10 border border-cyber-blue/30 rounded text-xs font-mono text-cyber-blue">Temporal Convolutions</div>
            </div>
          </div>
        </TiltCard>

        {/* Dataset */}
        <TiltCard className="col-span-1 row-span-1">
          <div className="flex flex-col h-full justify-between text-center items-center">
            <Database size={48} className="text-white/50 mb-4" />
            <h3 className="text-lg font-mono text-white mb-2">Training Corpus</h3>
            <p className="text-2xl font-black text-cyber-blue">4.2PB</p>
            <p className="text-xs font-mono text-gray-500 mt-2">Curated Synthetic Media</p>
          </div>
        </TiltCard>

        {/* Processing Speed */}
        <TiltCard className="col-span-1 row-span-1">
          <div className="flex flex-col h-full justify-between">
            <Zap size={32} className="text-alert-red" />
            <div>
              <p className="text-3xl font-black text-white mb-1">&lt; 150ms</p>
              <h3 className="text-sm font-mono text-gray-400">Inference Latency</h3>
            </div>
          </div>
        </TiltCard>

        {/* Algorithm details */}
        <TiltCard className="col-span-1 md:col-span-2 row-span-1 relative overflow-hidden">
          <div className="absolute inset-0 bg-[linear-gradient(45deg,transparent_25%,rgba(0,212,255,0.05)_50%,transparent_75%,transparent_100%)] bg-[length:250px_250px] animate-[shimmer_3s_infinite_linear]"></div>
          <div className="relative z-10 flex flex-col h-full justify-between">
            <div className="flex items-center gap-3 mb-4">
              <Cpu size={24} className="text-white" />
              <h3 className="text-lg font-mono text-white">Spectral Analysis Engine</h3>
            </div>
            <p className="text-sm font-sans text-gray-400">
              Deepfakes often leave imperceptible signatures in the frequency domain. Our spectral engine isolates high-frequency noise patterns generated by GANs and diffusion models, highlighting anomalies that are invisible to the naked eye.
            </p>
          </div>
        </TiltCard>
      </div>
    </motion.div>
  );
};

export default Research;
